In [5]:
##Install packages first, if you forget look up "How to install packages in pycharm/python"
##Manually, -m pip install [Package]
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os as os

In [7]:
os.getcwd() ##Get your working directory

'C:\\Users\\Nate'

In [10]:
#Making Data Frames and Matrices
k1 = pd.DataFrame({"Nate" : [1,5,6,7], "Barrett" : [4,2,3,1]}, index=["h","e","l","p"])
print(k1["Nate"])
print(k1["Nate"][0])

h    1
e    5
l    6
p    7
Name: Nate, dtype: int64
1


In [11]:
hf = np.array([(1,2,3,4),(5,6,7,8)],)
print(hf)
print(hf[0])
print(hf[0,1])

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
2


In [15]:
#Reading in Data
##Other ways such as using module "csv" but this is standard

Cars = pd.read_csv("cars04.csv")
Cars.head()

Vehicle Name  Hybrid  SuggestedRetailPrice  DealerCost  \
0           Chevrolet Aveo 4dr       0                 11690       10965   
1  Chevrolet Aveo LS 4dr hatch       0                 12585       11802   
2       Chevrolet Cavalier 2dr       0                 14610       13697   
3       Chevrolet Cavalier 4dr       0                 14810       13884   
4    Chevrolet Cavalier LS 2dr       0                 16385       15357   

   EngineSize  Cylinders  Horsepower  CityMPG  HighwayMPG  Weight  WheelBase  \
0         1.6          4         103       28          34    2370         98   
1         1.6          4         103       28          34    2348         98   
2         2.2          4         140       26          37    2617        104   
3         2.2          4         140       26          37    2676        104   
4         2.2          4         140       26          37    2617        104   

   Length  Width  
0     167     66  
1     153     66  
2     183     69  
3     183     68  
4     183     69

In [17]:
#Cleansing Data
##First check for interpretation error and inconsistencies manually first!!
##Usually applies to data entries when they don't have a certain value or a value is inconsistent with the rest
data = pd.Series([1, np.nan, 'hello', None])

In [18]:
print(data)

0        1
1      NaN
2    hello
3     None
dtype: object


In [21]:
##Fixing Null Values
###Finding null values

data.isnull()


0    False
1     True
2    False
3     True
dtype: bool

In [20]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [22]:
##Removing Null Values
###Be careful with this, you don't wanna get ahead of yourself

data.dropna()

0        1
2    hello
dtype: object

In [23]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [24]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [25]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [26]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [27]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [28]:
##Filling NA Values
###This is a much preferred method to dealing with NA values

data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [29]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [42]:
###forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [43]:
### back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [31]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [32]:
###On dataframes
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [33]:
##Fixing redundent Whitespace
###Usually, applies to columns more than anything to keep uniform syntax
###White spaces can cause errors and bugs when indexing for analysis
###Errors in strings if data frame has white space between characters in strings in some languages can ouput as NA

my_string = "  This   sentence    contains many redundant    whitespaces    !!!  "

In [34]:
###Remove space on the ends
my_string_1 = my_string.strip()
print(my_string_1)

This   sentence    contains many redundant    whitespaces    !!!


In [35]:
###Remove space to the right end of string
my_string_2 = my_string.rstrip()
print(my_string_2)

  This   sentence    contains many redundant    whitespaces    !!!


In [36]:
###Remove space to the left end of string
my_string_3 = my_string.lstrip()
print(my_string_3)

This   sentence    contains many redundant    whitespaces    !!!  


In [37]:
###Remove multiple spaces between characters
import re
my_string_4 = re.sub(" +", " ",my_string)
print(my_string_4)

 This sentence contains many redundant whitespaces !!! 


In [38]:
###Remove all the space
my_string_5 = my_string.replace(" ", "")
print(my_string_5)

Thissentencecontainsmanyredundantwhitespaces!!!


In [ ]:
##Application to dataframes
###Usually wanna use this set up when reading in "raw" data
#pd.read_table("Name of file.[format]", sep=r",", Names : [] )
##Does anyone have a text file?

In [40]:
Data2 = pd.read_table("data.csv", sep=r',', names=["Year", "Make", "Model", "Description"])
Data2 ###observe how the entries are not uniformly spaced.

Year     Make   Model              Description
0        1997     Ford    E350                      NaN
1        1997    Ford     E350                      NaN
2        1997     Ford    E350   Super, luxurious truck
3        1997     Ford    E350  Super "luxurious" truck
4        1997     Ford    E350   Super luxurious truck 
5      "1997"     Ford    E350                      NaN
6        1997     Ford    E350                      NaN
7        2000  Mercury  Cougar                      NaN

In [ ]:
##Using Converters
##Converters are applied objects of the read_[] method of pandas, can give special read functions to lines
##Helps make time when column has same problem with every entry

In [41]:
def strip(text):
    try:
        return text.strip()
    except AttributeError:
        return text

def make_int(text):
    return int(text.strip('" '))

table = pd.read_table("data.csv", sep=r',',
                      names=["Year", "Make", "Model", "Description"],
                      converters = {'Description' : strip,
                                    'Model' : strip,
                                    'Make' : strip,
                                    'Year' : make_int})
print(table)

##Noticed how it didn't fix everything...

   Year     Make   Model              Description
0  1997     Ford    E350                         
1  1997     Ford    E350                         
2  1997     Ford    E350   Super, luxurious truck
3  1997     Ford    E350  Super "luxurious" truck
4  1997     Ford    E350    Super luxurious truck
5  1997     Ford    E350                         
6  1997     Ford    E350                         
7  2000  Mercury  Cougar                         
